export const TEACHERS = [
  'Bodirwa Morake Edwin',
  'Chimurudze Anywhere',
  'Chinyengetere Evidence Mufaro',
  'Chiwara Grace',
  'Datnow Jarin',
  'Dube Nompumelelo Catherine',
  'Dube Sithokozile',
  'Fakude Evidence Nicholus',
  'Gwintsa Emmanuel',
  'Halgryn Roan',
  'Hlatshwayo Muriel Nonhlanhla',
  'Khanye Siphokazi Olga',
  'Lottering Marli',
  'Magwaza Ernest',
  'Mahlalela Thomas',
  'Makhomisani Portia',
  'Makombe Shalon',
  'Mandigora Mildred',
  'Maritz Simone',
  'Masuku Silindokuhle Sinesipho',
  'Mathebula Nompumelelo',
  'Mazambara Progress',
  'Mazibuko Slindokuhle',
  'Maziya Thembelihle',
  'Mbatha Nokulunga Nompilo',
  'Meja Peisai',
  'Mlilo Ngqabutho',
  'Moller Tanya',
  'Moremi Kwena Ruth',
  'Moyo Similo',
  'Mpondo Nabien',
  'Ncube Gloria',
  'Ndiweni Mkhululi',
  'Ndlovu Felicia Fikile',
  'Ngwaru Tineyi',
  'Ngwenya Cosmas',
  'Ngwenya Nomathemba',
  'Nkosi Nonzuzo Fezile',
  'Ntshangase Collet Nortia Thandekile',
  'Ntshangase Siphesihle Melokuhle',
  'Oosthuizen Johanne',
  'Philpott Maritha Madelein',
  'Sangweni Sibonile',
  'Sebeya Gift Khethiwe',
  'Shiku Bruce',
  'Sithole Zanele Cindy',
  'Thebe NomaZulu',
  'Theron Mialette',
  'Tigere Charity',
  'Tshuma Gugulethu',
  'Wonja Arnauld Josue',
  'Zwane Nothemba',
]
